package net.cubizor.runtimedependency

import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property

/**
 * Paper mode extension for runtime dependency loading in Paper plugins.
 *
 * This mode generates a PluginLoader class that Paper will use to load
 * dependencies at runtime from Maven repositories.
 *
 * Example:
 * ```kotlin
 * runtimeDependency {
 *     paper {
 *         enabled.set(true)
 *         loaderPackage.set("com.example.loader")
 *         loaderClassName.set("DependencyLoader")
 *     }
 * }
 *
 * dependencies {
 *     runtimeDownload("com.google.code.gson:gson:2.10.1")
 * }
 * ```
 */
abstract class PaperExtension {
    abstract val enabled: Property<Boolean>
    abstract val loaderPackage: Property<String>
    abstract val loaderClassName: Property<String>
    abstract val excludes: ListProperty<String>

    init {
        enabled.convention(false)
        loaderPackage.convention("net.cubizor.loader")
        loaderClassName.convention("AutoGeneratedPluginLoader")
        excludes.convention(emptyList())
    }
}

abstract class RuntimeDependencyExtension {
    abstract val outputDirectory: Property<String>
    abstract val organizeByGroup: Property<Boolean>

    init {
        outputDirectory.convention("runtime-dependencies")
        organizeByGroup.convention(true)
    }
}

