package net.cubizor.gradle

import org.gradle.api.provider.Property

abstract class PaperExtension {
    abstract val enabled: Property<Boolean>
    abstract val loaderPackage: Property<String>
    abstract val loaderClassName: Property<String>

    init {
        enabled.convention(false)
        loaderPackage.convention("net.cubizor.loader")
        loaderClassName.convention("AutoGeneratedPluginLoader")
    }
}

abstract class StandaloneExtension {
    abstract val enabled: Property<Boolean>
    abstract val mainClass: Property<String>
    abstract val libraryPath: Property<String>
    abstract val includeBootstrapInJar: Property<Boolean>

    init {
        enabled.convention(false)
        mainClass.convention("")
        libraryPath.convention("runtime-dependencies")
        includeBootstrapInJar.convention(true)
    }
}

abstract class RuntimeDependencyExtension {
    abstract val outputDirectory: Property<String>
    abstract val organizeByGroup: Property<Boolean>

    init {
        outputDirectory.convention("runtime-dependencies")
        organizeByGroup.convention(true)
    }
}
